In [1]:
from gym import Env
from gym.spaces import Discrete, Box
import numpy as np


In [2]:
from collections import deque

def BFS(board, start_row, start_col):
  level = [[0]*5 for i in range(5)]
  #Stay Up Right Down Left, UR, DR, DL, UL
  dr = [0,-1,0,1,0, -1,1,1,-1]
  dc = [0,0,1,0,-1,1,1,-1,-1]

  result = 0
  if board[start_row][start_col] == 1 or board[start_row][start_col] == 2:
    return 0

  queue = deque([])
  visited = [[False]*5 for i in range(5)]
  
  level[start_row][start_col] = 1
  visited[start_row][start_col] = True
  queue.append((start_row,start_col))

  while(len(queue) != 0):
    (row,col) = queue.popleft()
    #result = result + 1
    result = result + (10-level[row][col])*5

    for i in range(9):
      nr = row + dr[i]
      nc = col + dc[i]
      if nr < 0 or nr >= 5 or nc < 0 or nc >= 5:
        continue
      if board[nr][nc] == 1 or board[nr][nc] == 2: #여기수정
        continue
      if visited[nr][nc] == True:
        continue

      visited[nr][nc] = True
      if i<=4:
        level[nr][nc] = level[row][col] +1
      else:
        level[nr][nc] = level[row][col] +1+0.5
      queue.append((nr,nc))

  return result


temp = [[0]*5 for i in range(5)]

BFS(temp,1,1)


827.5

In [3]:
import copy
from tabulate import tabulate
import random

class BingoEnv(Env):
  def __init__(self):
    self.round = 0
    self.action_space = Discrete(25)
    #self.observation_space = Box(low=0, high=2, shape=(15,5,5), dtype=np.int32)
    self.observation_space = Box(low = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]), high = np.array([2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,10]),dtype=np.int32)
 
    #self.state = np.zeros((15,5,5))
    self.state = np.zeros(26)
    
    self.first_rand_pos = random.choice([i for i in range(0,25) if i not in [6]])
    self.second_rand_pos = random.choice([i for i in range(0,25) if i not in [6,self.first_rand_pos]])
    self.state[self.first_rand_pos] = 1
    self.state[self.second_rand_pos] = 1



  def check_bingo(self, board, row,col):
    result_list = []

    result = 1
    for i in range(5):
      result = result * board[row][i]
      if result == 0:
        break
    if result > 0:
      result_list.append("ROW")
    
    result = 1
    for i in range(5):
      result = result * board[i][col]
      if result == 0:
        break
    if result > 0:
      result_list.append("COL")

    if row == col:
      result = 1
      result = result * board[0][0] * board[1][1] * board[2][2] * board[3][3] * board[4][4]
      if result > 0:
        result_list.append("LC")

    if row+col == 4:
      result = 1
      result = result * board[0][4] * board[1][3] * board[2][2] * board[3][1] * board[4][0]
      if result > 0 :
        result_list.append("RC")

    return result_list

  def step(self, action):
    #self.round = self.round+1
    #cur_board = self.state[self.round]
    #self.state[self.round] = copy.deepcopy(self.state[self.round-1])
    self.round = self.state[-1] + 1
    self.state = self.state[:-1].reshape(5,5)
    row = action // 5
    col = action % 5
    bingo_count = 0
    #canClick = False

#None Up Right Down Left
    dr = [0,-1,0,1,0]
    dc = [0,0,1,0,-1]
    before_num = [-1,-1,-1,-1,-1]
    for i in range(5):
      nr = row + dr[i]
      nc = col + dc[i]
      if nr < 0 or nr >= 5 or nc < 0 or nc >= 5:
        continue

      if self.state[nr][nc] == 2:
        before_num[i] = 2
        continue

      elif self.state[nr][nc] == 1:
        before_num[i] = 1
        self.state[nr][nc] = 0
        
      elif self.state[nr][nc] == 0:
        before_num[i] = 0
        self.state[nr][nc] = 1
      
    for i in range(5):
      nr = row + dr[i]
      nc = col + dc[i]
      if before_num[i] == 2:
        continue
      if nr < 0 or nr >= 5 or nc < 0 or nc >= 5:
        continue

      if self.state[nr][nc] != 0:
        isBingo = self.check_bingo(self.state,nr,nc)
        bingo_count = bingo_count + len(isBingo)

        for dir in isBingo:
          if dir == "ROW":
            for i in range(5):
              self.state[nr][i] = 2
          elif dir == "COL":
            for i in range(5):
              self.state[i][nc] = 2
          elif dir == "LC":
            self.state[0][0] = 2
            self.state[1][1] = 2
            self.state[2][2] = 2
            self.state[3][3] = 2
            self.state[4][4] = 2
          elif dir == "RC":
            self.state[0][4] = 2
            self.state[1][3] = 2
            self.state[2][2] = 2
            self.state[3][1] = 2
            self.state[4][0] = 2
    
    
    three_bingo = True
    #rest_block_score = BFS(self.state,1,1) / 100
    #rest_block_score = BFS(self.state,1,1) / 50
    rest_block_score = BFS(self.state,1,1) / 10

    if self.round % 3 == 0 and bingo_count == 0:
      three_bingo = False
    else:
      reward = rest_block_score
    #elif self.round % 3 == 0 and bingo_count > 0:
    #  reward = (2/bingo_count) + rest_block_score
    #elif self.round % 3 != 0 and bingo_count > 0:
    #  reward = -0.5 * bingo_count + rest_block_score
    #else:
    #  reward = rest_block_score

    board_sum = 0
    for i in range(5):
      for j in range(5):
        board_sum = board_sum + self.state[i][j]

    if (board_sum == 50) or self.round == 9 or three_bingo == False:
      done = True
      if self.round == 9 and three_bingo == True:
        reward = rest_block_score
      else:
        reward = -100
    else:
      done = False
    
    #if done == False:
    #  reward += 1
    
    info ={}
    self.state = np.append(self.state.reshape(25),self.round)
    return self.state, reward, done, info

  def render(self):
    print("ROUND : ",self.state[-1])
    print(tabulate(self.state[0:25].reshape(5,5)))

  def reset(self):
    self.state = np.zeros(26)
    
    self.first_rand_pos = random.choice([i for i in range(0,25) if i not in [6]])
    self.second_rand_pos = random.choice([i for i in range(0,25) if i not in [6,self.first_rand_pos]])
    self.state[self.first_rand_pos] = 1
    self.state[self.second_rand_pos] = 1
    return self.state


#t = BingoEnv()
#t.render()
#t.step(0)
#t.step(3)
#t.step(9)
#t.step(24)

In [4]:
a= np.array([5,4,3])
a = a[-1] + 7
print(a)
np.zeros((1,5))

10


array([[0., 0., 0., 0., 0.]])

In [5]:
env = BingoEnv()
episodes = 10
for episode in range(1,episodes+1):
  state = env.reset()
  done = False
  reward_sum = 0

  while not done:
    env.render()
    action = env.action_space.sample()
    n_state, reward, done, info = env.step(action)
    reward_sum += reward

  env.render()
  print("Episode : {} reward_sum : {}".format(episode, reward_sum))

ROUND :  0.0
-  -  -  -  -
0  0  0  0  0
0  0  0  0  0
0  0  0  0  0
0  1  0  0  0
0  0  0  1  0
-  -  -  -  -
ROUND :  1.0
-  -  -  -  -
0  0  1  1  1
0  0  0  1  0
0  0  0  0  0
0  1  0  0  0
0  0  0  1  0
-  -  -  -  -
ROUND :  2.0
-  -  -  -  -
0  0  1  1  1
0  0  0  1  0
0  0  0  0  0
0  1  0  0  1
0  0  0  0  1
-  -  -  -  -
ROUND :  3.0
-  -  -  -  -
0  0  1  1  1
0  0  0  1  0
0  1  0  0  0
1  0  1  0  1
0  1  0  0  1
-  -  -  -  -
Episode : 1 reward_sum : 22.75
ROUND :  0.0
-  -  -  -  -
0  0  0  0  0
0  0  0  0  0
1  0  0  0  0
1  0  0  0  0
0  0  0  0  0
-  -  -  -  -
ROUND :  1.0
-  -  -  -  -
0  0  0  0  0
0  1  0  0  0
0  1  1  0  0
1  1  0  0  0
0  0  0  0  0
-  -  -  -  -
ROUND :  2.0
-  -  -  -  -
0  0  1  1  1
0  1  0  1  0
0  1  1  0  0
1  1  0  0  0
0  0  0  0  0
-  -  -  -  -
ROUND :  3.0
-  -  -  -  -
0  1  1  1  1
1  0  1  1  0
0  0  1  0  0
1  1  0  0  0
0  0  0  0  0
-  -  -  -  -
Episode : 2 reward_sum : -100.0
ROUND :  0.0
-  -  -  -  -
0  0  0  0  0
0  0  0 

In [6]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam

In [7]:
def build_model(states, actions):
  model = Sequential()
  model.add(Flatten(input_shape=(1,26)))
  model.add(Dense(50, activation='relu'))
  model.add(Dense(50, activation='relu'))
  model.add(Dense(actions,activation='linear'))
  return model

In [14]:
del model

In [15]:
states = env.observation_space.shape
actions = env.action_space.n
model = build_model(states,actions)


In [16]:
model.summary()
states

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 26)                0         
                                                                 
 dense_3 (Dense)             (None, 50)                1350      
                                                                 
 dense_4 (Dense)             (None, 50)                2550      
                                                                 
 dense_5 (Dense)             (None, 25)                1275      
                                                                 
Total params: 5,175
Trainable params: 5,175
Non-trainable params: 0
_________________________________________________________________


(26,)

In [11]:
!pip install keras-rl2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 52 kB 323 kB/s 


In [17]:
from rl.agents import DQNAgent
from rl.policy import BoltzmannQPolicy
from rl.memory import SequentialMemory
from rl.policy import EpsGreedyQPolicy

def build_agent(model, actions):
  policy = BoltzmannQPolicy()
  memory = SequentialMemory(limit=50000,window_length=1)
  dqn = DQNAgent(model= model, memory = memory, policy= policy, nb_actions=actions, nb_steps_warmup=1000,target_model_update=1e-2)
  return dqn

In [18]:
dqn = build_agent(model, actions)
dqn.compile(Adam(learning_rate=0.0005), metrics=["mse"])
#dqn.fit(env,nb_steps = 200000, visualize= False, verbose=1) #  더 학습시킬 때는 아래 있는 코드를 이용해라!!!!!

In [22]:
scores = dqn.test(env, nb_episodes=100, visualize=False)
print(np.mean(scores.history['episode_reward']))

Testing for 100 episodes ...
Episode 1: reward: 354.250, steps: 9
Episode 2: reward: 394.000, steps: 9
Episode 3: reward: 364.750, steps: 9
Episode 4: reward: 421.250, steps: 9
Episode 5: reward: 390.250, steps: 9
Episode 6: reward: 410.750, steps: 9
Episode 7: reward: 384.500, steps: 9
Episode 8: reward: 239.750, steps: 9
Episode 9: reward: 393.750, steps: 9
Episode 10: reward: 359.250, steps: 9
Episode 11: reward: 177.750, steps: 6
Episode 12: reward: 394.250, steps: 9
Episode 13: reward: 403.000, steps: 9
Episode 14: reward: 377.750, steps: 9
Episode 15: reward: 403.000, steps: 9
Episode 16: reward: 254.000, steps: 9
Episode 17: reward: 399.500, steps: 9
Episode 18: reward: 400.500, steps: 9
Episode 19: reward: 383.250, steps: 9
Episode 20: reward: 389.750, steps: 9
Episode 21: reward: 378.500, steps: 9
Episode 22: reward: 360.750, steps: 9
Episode 23: reward: 328.000, steps: 9
Episode 24: reward: 344.750, steps: 9
Episode 25: reward: 408.500, steps: 9
Episode 26: reward: 344.750, s

In [ ]:
model.save('9round_final.h5')

In [21]:
dqn.fit(env,nb_steps = 200000, visualize= False, verbose=1)

Training for 200000 steps ...
Interval 1 (0 steps performed)
10000/10000 [==============================] - 14s 1ms/step - reward: 37.5416
1178 episodes - episode_reward: 318.481 [16.500, 445.500]

Interval 2 (10000 steps performed)
10000/10000 [==============================] - 15s 1ms/step - reward: 37.2053
1192 episodes - episode_reward: 312.085 [16.500, 445.500]

Interval 3 (20000 steps performed)
10000/10000 [==============================] - 14s 1ms/step - reward: 37.2801
1187 episodes - episode_reward: 314.170 [16.500, 445.500]

Interval 4 (30000 steps performed)
10000/10000 [==============================] - 14s 1ms/step - reward: 37.4971
1179 episodes - episode_reward: 317.919 [16.500, 445.500]

Interval 5 (40000 steps performed)
10000/10000 [==============================] - 14s 1ms/step - reward: 36.8883
1187 episodes - episode_reward: 310.681 [16.500, 445.500]

Interval 6 (50000 steps performed)
10000/10000 [==============================] - 14s 1ms/step - reward: 37.4034
1

-4.5

In [44]:
class TestBingoEnv(Env):
  def __init__(self,state):
    self.round = state[-1]
    self.action_space = Discrete(25)
    self.observation_space = Box(low = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]), high = np.array([2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,10]),dtype=np.int32)
    self.state = state



  def check_bingo(self, board, row,col):
    result_list = []

    result = 1
    for i in range(5):
      result = result * board[row][i]
      if result == 0:
        break
    if result > 0:
      result_list.append("ROW")
    
    result = 1
    for i in range(5):
      result = result * board[i][col]
      if result == 0:
        break
    if result > 0:
      result_list.append("COL")

    if row == col:
      result = 1
      result = result * board[0][0] * board[1][1] * board[2][2] * board[3][3] * board[4][4]
      if result > 0:
        result_list.append("LC")

    if row+col == 4:
      result = 1
      result = result * board[0][4] * board[1][3] * board[2][2] * board[3][1] * board[4][0]
      if result > 0 :
        result_list.append("RC")

    return result_list

  def step(self, action):
    #self.round = self.round+1
    #cur_board = self.state[self.round]
    #self.state[self.round] = copy.deepcopy(self.state[self.round-1])
    self.round = self.state[-1] + 1
    self.state = self.state[:-1].reshape(5,5)
    row = action // 5
    col = action % 5
    bingo_count = 0
    canClick = False

#None Up Right Down Left
    dr = [0,-1,0,1,0]
    dc = [0,0,1,0,-1]
    before_num = [-1,-1,-1,-1,-1]
    for i in range(5):
      nr = row + dr[i]
      nc = col + dc[i]
      if nr < 0 or nr >= 5 or nc < 0 or nc >= 5:
        continue

      if self.state[nr][nc] == 2:
        before_num[i] = 2
        continue

      elif self.state[nr][nc] == 1:
        before_num[i] = 1
        self.state[nr][nc] = 0
        
      elif self.state[nr][nc] == 0:
        before_num[i] = 0
        self.state[nr][nc] = 1
      
    for i in range(5):
      nr = row + dr[i]
      nc = col + dc[i]
      if before_num[i] == 2:
        continue
      if nr < 0 or nr >= 5 or nc < 0 or nc >= 5:
        continue

      if self.state[nr][nc] != 0:
        isBingo = self.check_bingo(self.state,nr,nc)
        bingo_count = bingo_count + len(isBingo)

        for dir in isBingo:
          if dir == "ROW":
            for i in range(5):
              self.state[nr][i] = 2
          elif dir == "COL":
            for i in range(5):
              self.state[i][nc] = 2
          elif dir == "LC":
            self.state[0][0] = 2
            self.state[1][1] = 2
            self.state[2][2] = 2
            self.state[3][3] = 2
            self.state[4][4] = 2
          elif dir == "RC":
            self.state[0][4] = 2
            self.state[1][3] = 2
            self.state[2][2] = 2
            self.state[3][1] = 2
            self.state[4][0] = 2
        
    
    three_bingo = True
    #rest_block_score = BFS(self.state,1,1) / 100
    #rest_block_score = BFS(self.state,1,1) / 50
    rest_block_score = BFS(self.state,1,1) / 10

    if self.round % 3 == 0 and bingo_count == 0:
      three_bingo = False
    else:
      reward = rest_block_score
    #elif self.round % 3 == 0 and bingo_count > 0:
    #  reward = (2/bingo_count) + rest_block_score
    #elif self.round % 3 != 0 and bingo_count > 0:
    #  reward = -0.5 * bingo_count + rest_block_score
    #else:
    #  reward = rest_block_score

    board_sum = 0
    for i in range(5):
      for j in range(5):
        board_sum = board_sum + self.state[i][j]

    if (board_sum == 50) or self.round == 9 or three_bingo == False:
      done = True
      if self.round == 9 and three_bingo == True:
        reward = rest_block_score
      else:
        reward = -100
    else:
      done = False
    
    #if done == False:
    #  reward += 1

    info ={}
    self.state = np.append(self.state.reshape(25),self.round)
    return self.state, reward, done, info

  def render(self):
    print("ROUND : ",self.state[-1])
    print(tabulate(self.state[0:25].reshape(5,5)))

  def reset(self):
    self.state = np.zeros(26)
    
    self.first_rand_pos = random.choice([i for i in range(0,25) if i not in [6]])
    self.second_rand_pos = random.choice([i for i in range(0,25) if i not in [6,self.first_rand_pos]])
    self.state[self.first_rand_pos] = 1
    self.state[self.second_rand_pos] = 1
    return self.state

In [54]:

test_state = np.zeros(26)
test_first_rand_pos = random.choice([i for i in range(0,25) if i not in [6]])
test_second_rand_pos = random.choice([i for i in range(0,25) if i not in [6,test_first_rand_pos]])
test_state[test_first_rand_pos] = 1
test_state[test_second_rand_pos] = 1

t = TestBingoEnv(test_state)
t.render()
#tt = TestBingoEnv(np.array([1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,1,0,0,0,2]))
#tt.render()
#tt_state,_,_,_ = tt.step(6)
#print(tt_state[0:25].reshape(5,5))

#
#ROUND :  0.0
#-  -  -  -  -
#0  0  0  0  0
#0  0  0  0  0
#0  1  0  0  0
#0  1  0  0  0
#0  0  0  0  0
#-  -  -  -  -
# 이 경우 saved_model_14round 잘작동

ROUND :  0.0
-  -  -  -  -
0  0  0  0  0
0  0  0  0  0
1  0  0  0  0
0  0  0  1  0
0  0  0  0  0
-  -  -  -  -


In [63]:
#반복
print("before")
print(t.state[0:25].reshape(5,5))
cell_num = np.argmax(model.predict(t.state.reshape(1,1,26)))
temp_state,tmp_reward,tmp_done,_ = t.step(cell_num)

print('ROUND : ',temp_state[-1])
print('cell_num : ',cell_num)
print("action : ",cell_num //5 , cell_num %5)
print(temp_state[0:25].reshape(5,5))
print(tmp_reward,tmp_done)
print("-------------------------------")

before
[[0. 0. 0. 0. 2.]
 [0. 0. 0. 2. 2.]
 [2. 2. 2. 2. 2.]
 [0. 2. 1. 0. 2.]
 [2. 2. 2. 2. 2.]]
ROUND :  9.0
cell_num :  6
action :  1 1
[[0. 2. 0. 0. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [0. 2. 1. 0. 2.]
 [2. 2. 2. 2. 2.]]
0.0 True
-------------------------------


In [ ]:
print(BFS([[1, 1, 0, 0, 2],
 [1, 0, 1, 2, 2],
 [0, 0, 2, 1, 2],
 [2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2],],1,1))

print(BFS([[0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 1, 1],
 [1, 0, 0, 0, 0],
 [1, 1, 0, 0, 0]],1,1))

75
195


In [ ]:
tmp_actions = model.predict(np.array([0, 0, 0, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0,
 1, 0, 0, 0, 0,
 0, 1, 0, 0, 0, 0]).reshape(1,1,26))
print(tmp_actions)
tmp_num = np.argmax(tmp_actions)
print(tmp_num//5,tmp_num%5)

[[ -81.620514  -94.453835  -81.42285   -80.62964   -80.356995  -94.5878
   -98.66935   -95.862755  -81.02263   -80.79095   -79.92034   -90.25046
   -81.07934   -80.87428   -80.09678   -79.64154   -79.9207    -79.938736
   -88.60145   -83.07046   -79.84846   -80.0151    -93.35611  -107.32624
   -96.846436]]
3 0


In [ ]:
#del model
import tensorflow as tf
model = tf.keras.models.load_model('electron_model_v3.h5')

In [ ]:
dqn = build_agent(model, actions)
dqn.compile(Adam(learning_rate=1e-3), metrics=["mse"])

In [ ]:
with tf.device('/device:GPU:0'):
  dqn.fit(env,nb_steps = 10000, visualize= False, verbose=1)

Training for 1000 steps ...
Interval 1 (0 steps performed)


/usr/local/lib/python3.7/dist-packages/keras/engine/training_v1.py:2079: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


    1/10000 [..............................] - ETA: 37:40 - reward: 63.0000

/usr/local/lib/python3.7/dist-packages/rl/memory.py:37: UserWarning: Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!
  warnings.warn('Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!')


  997/10000 [=>............................] - ETA: 2:03 - reward: 40.3380done, took 13.897 seconds


In [ ]:
model.save("electron_model_v3.h5")

reward 수정

In [ ]:
from tensorflow.python.client import device_lib
#print(device_lib.list_local_devices())


import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [ ]:
from rl.agents import DQNAgent
from rl.policy import BoltzmannQPolicy
from rl.memory import SequentialMemory
tf.debugging.set_log_device_placement(True)
with tf.device('/GPU:0'):
  gpu_model = Sequential()
  gpu_model.add(Flatten(input_shape=(1,26)))
  gpu_model.add(Dense(50, activation='relu'))
  gpu_model.add(Dense(50, activation='relu'))
  gpu_model.add(Dense(actions,activation='linear'))
  a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])

  c = tf.matmul(a, b)
  print(c)  
  gpu_model.summary()
  print(gpu_model)
  
  gpu_policy = BoltzmannQPolicy()
  gpu_memory = SequentialMemory(limit=50000,window_length=1)
  gpu_dqn = DQNAgent(model= gpu_model, memory = gpu_memory, policy= gpu_policy, nb_actions=actions, nb_steps_warmup=10,target_model_update=1e-2)
  gpu_dqn.compile(Adam(learning_rate=1e-3), metrics=["mae"])

  gpu_dqn.fit(env,nb_steps = 10000, visualize= False, verbose=1)

  

Tensor("MatMul_7:0", shape=(2, 2), dtype=float32, device=/device:GPU:0)
Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_7 (Flatten)         (None, 26)                0         
                                                                 
 dense_21 (Dense)            (None, 50)                1350      
                                                                 
 dense_22 (Dense)            (None, 50)                2550      
                                                                 
 dense_23 (Dense)            (None, 25)                1275      
                                                                 
Total params: 5,175
Trainable params: 5,175
Non-trainable params: 0
_________________________________________________________________
Training for 10000 steps ...
Interval 1 (0 steps performed)


/usr/local/lib/python3.7/dist-packages/keras/engine/training_v1.py:2079: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


    1/10000 [..............................] - ETA: 43:10 - reward: 0.7000

/usr/local/lib/python3.7/dist-packages/rl/memory.py:37: UserWarning: Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!
  warnings.warn('Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!')


 3902/10000 [==========>...................] - ETA: 1:44 - reward: -30.2383done, took 67.355 seconds


In [ ]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 10666592694238258993
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 11320098816
locality {
  bus_id: 1
  links {
  }
}
incarnation: 7164466880925710482
physical_device_desc: "device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7"
xla_global_id: 416903419
]


In [ ]:
!pip install tensorflowjs

     |████████████████████████████████| 77 kB 4.3 MB/s 


In [ ]:
model.save("test.h5")

In [ ]:
!tensorflowjs_converter --input_format keras ./test.h5 ./

In [ ]:
import tensorflowjs as tfjs

tfjs.converters.save_keras_model(model, "./")